### PR TITLE
Add account_file touch to determine current logged in account by modified date

### PR DESCRIPTION
**Pull request by rikkipitt**
This addition is for helping determine the currently logged in account by touching the account_file after an account has been set. We can use this information to have a command line prompt to show which account is logged in by use of modified date.

### CODE REVIEW

**Comment by rikkipitt** [comment]
I've also added a convenience method to display just the current account with `heroku accounts:current`. This is based off the modified times of the accounts files so as to not ping Heroku.

**Comment by dickeyxxx** [comment]
Rather than have separate files for each account, wouldn't it be better to have this as a property in the netrc file?

**Comment by rikkipitt** [comment]
Hi @dickeyxxx multiple files is how it currently works, I'm just touching the currently logged in one.

This was an alternative suggestion after you commented on my netrc suggestion here - https://github.com/heroku/heroku-cli/issues/218

Which way would you prefer?

Cheers,
Rikki

**Comment by dickeyxxx** [comment]
I would definitely prefer for it to be in the netrc file

**Pull request closed without merging**
